openapi: "3.0.2"
info:
  title: Base Types for well defined GEOJson API elements
  version: "1.0.0"
  description: |
    These types are inteded to use them in allOf definitions for your own, well defined types.
    Example:
      ```yaml
      SpecificFeatureCollection:
        allOf:
        - $ref: path_to_spec#/components/schemas/FeatureCollectionType"
        - type: object
          properties:
            features:
              type: array
              items: 
                $ref: "#/components/schemas/SpecificFeature"
          required:
           - type
           - features
           
      SpecificFeature:
        allOf:
        - $ref: "path_to_spec#/components/schemas/MultiPolygonFeature"
        - type: object
          properties:
            id:
              type: string
            properties:
              $ref: "#/components/schemas/SpecificProperties"
          required:
            - id
            - properties
      SpecificProperties:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          someFlag:
            type: boolean
      ```
paths:
  /dummy:
    respones:
      200:
        description: dummy
        
components:
  schemas:
    FeatureCollectionType:
      type: string
      enum:
        - FeatureCollection
      default: FeatureCollection

    FeatureType:
      type: string
      enum:
        - Feature
      default: Feature

    Position:
      type: array
      minItems: 2
      maxItems: 3
      items:
        type: number
      example: [ 50.12345, 10.12345 ]

    Point:
      type: object
      properties:
        type:
          type: string
          enum: [ Point ]
          default: Point
        coordinates:
          $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates

    MultiPoint:
      type: object
      properties:
        type:
          type: string
          enum: [ MultiPoint ]
          default: MultiPoint
        coordinates:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates

    LineString:
      type: object
      properties:
        type:
          type: string
          enum: [ LineString ]
          default: LineString
        coordinates:
          type: array
          minItems: 2
          items:
            $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates

    MultiLineString:
      type: object
      properties:
        type:
          type: string
          enum: [ MultiLineString ]
          default: MultiLineString
        coordinates:
          type: array
          minItems: 1
          items:
            type: array
            minItems: 2
            items:
              $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates
    
    Polygon:
      type: object
      properties:
        type:
          type: string
          enum: [ Polygon ]
          default: Polygon
        coordinates:
          type: array
          minItems: 1
          items:
            type: array
            minItems: 4
            items:
              $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates
    
    MultiPolygon:
      type: object
      properties:
        type:
          type: string
          enum: [ MultiPolygon ]
          default: MultiPolygon
        coordinates:
          type: array
          minItems: 1
          items:
            type: array
            minItems: 1
            items:
              type: array
              minItems: 4
              items:
                $ref: "#/components/schemas/Position"
      required:
        - type
        - coordinates
        
    PointFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/Point"
      required:
        - type
        - geometry
    
    MutliPointFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/MultiPoint"
      required:
        - type
        - geometry

    LineStringFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/LineString"
      required:
        - type
        - geometry

    MultiLineStringFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/MultiLineString"
      required:
        - type
        - geometry

    PolygonFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/Polygon"
      required:
        - type
        - geometry

    MultiPolygonFeature:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeatureType"
        geometry:
          $ref: "#/components/schemas/MultiPolygon"
      required:
        - type
        - geometry
